spring.application.name=TutoSpringWeb.jpa

#Database
spring.datasource.url = jdbc:mariadb://localhost:3307/tutospring?createDatabaseIfNotExist=true
spring.datasource.username = tutospringshop
spring.datasource.password = 7u705Pr1nG5h0P
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver

#Jpa-Hibernate
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDB53Dialect

# Thymeleaf
spring.thymeleaf.cache = false